# Generated by Django 3.2.4 on 2021-07-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likers',
        ),
    ]
