# Generated by Django 3.2.15 on 2023-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('PROG', 'Programming'), ('LIFE', 'Life Stories'), ('WRITTEN', 'Written Stories'), ('MISC', 'Miscellaneous')], default='LIFE', max_length=120),
        ),
    ]
